apiVersion: v1
kind: Service
metadata:
  name: web-svc-lb-coredns-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: 172.17.255.10
spec:
  externalTrafficPolicy: Local
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53
  loadBalancerIP: 172.17.255.10
---        
apiVersion: v1
kind: Service
metadata:
  name: web-svc-lb-coredns-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: 172.17.255.10
spec:
  externalTrafficPolicy: Local
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
  loadBalancerIP: 172.17.255.10
