apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-jane-admin
  namespace: dev
subjects:
- kind: ServiceAccount
  namespace: dev
  name: jane
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
