apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-ken-view
  namespace: dev
subjects:
- kind: ServiceAccount
  namespace: dev
  name: ken
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
