apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: prometheus
  name: pod-get-list-watch
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-pod-get-list-watch
  namespace: prometheus
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io  
  namespace: prometheus
roleRef:
  kind: ClusterRole
  name: pod-get-list-watch
  apiGroup: rbac.authorization.k8s.io
