apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alpine
  name: ken-test-alpine
  namespace: dev
spec:
  containers:
  - args:
    - /bin/sh
    image: alpine
    imagePullPolicy: Always
    name: alpine
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: ken
  serviceAccountName: ken
  terminationGracePeriodSeconds: 30
