apiVersion: v1
kind: Namespace
metadata:
  name: nginx-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter-deployment
  labels:
    app: nginx-exporter
  namespace: nginx-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-exporter
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.9.0
        args: ["-nginx.scrape-uri=http://nginx-status-page-service.nginx-status-page.svc.cluster.local:8000/basic_status"]
        ports:
        - containerPort: 9113
