apiVersion: v1
kind: Service
metadata:
  name: nginx-status-page-service
  namespace: nginx-status-page
spec:
  selector:
    app: nginx-status-page
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
