apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor1
  namespace: nginx-exporter
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: nginx-exporter-service
  endpoints:
  - port: web
